export WORK_HOME=$HOME/dev
export WORK_ORG=cramm-corp
export WORK_WIFI_CIDR=192.168.1.1/24
export GITHUB_USERNAME=beverts312
export DEV_ENV_HOME=$HOME/dev-env
export DEV_HOME=$WORK_HOME
export WORK_REGISTRY=dell.local:5000
export BACKUP_BUCKET=b4llz-quick-back
export BACKUP_ARGS="--endpoint-url=https://s3.wasabisys.com"
export DEFAULT_REMOTE=origin