version: "3.9"
services:
  m:
    user: 1000:1000
    image: beverts312/maxim
    volumes:
      - ./volumes/pretrained:/home/mluser/maxim/pretrained
      - ./volumes/working:/home/mluser/working
    environment:
      - NVIDIA_DISABLE_REQUIRE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
