version: "3.9"
services:
  bg-remover:
    image: beverts312/easy-ocr
    volumes:
      - ./volumes/working:/home/mluser/working
    environment:
      - NVIDIA_DISABLE_REQUIRE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
