version: "3.9"
services:
  gfpgan:
    image: beverts312/gfpgan
    volumes:
      - ./volumes/model:/home/mluser/gfpgan/experiments/pretrained_models
      - ./volumes/working:/home/mluser/working
    environment:
      - NVIDIA_DISABLE_REQUIRE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
